### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by vesakoo** [fmidev/opendata-resources#14]
At least these symbols are missing from SmartSybmols (dark and light): 
157.svg
107.svg

**Comment by vesakoo** [comment]
More missing symbols in use on fmi:
107 
 157
158
 148
149
138
111
(one can get a close match with minus 100)

**Comment by sirviot** [comment]
This should be fixed with the latest pull request #15 

All weather symbols didn't have a dedicated night version of them, and they were omitted in files. Now there are two image files to visualize for example fog. Although it is the same file for day and night time, it is easier to use the symbol set now.
